stock_choices = [
	{"label": "AAPL", "value": "AAPL"},
	{"label": "MSFT", "value": "MSFT"},
	{"label": "GOOG", "value": "GOOG"},
	{"label": "GOOGL", "value": "GOOGL"},
	{"label": "AMZN", "value": "AMZN"},
	{"label": "FB", "value": "FB"},
	{"label": "TSLA", "value": "TSLA"},
	{"label": "TSM", "value": "TSM"},
	{"label": "NVDA", "value": "NVDA"},
	{"label": "JPM", "value": "JPM"},
	{"label": "V", "value": "V"},
	{"label": "BABA", "value": "BABA"},
	{"label": "IDXX", "value": "IDXX"},
	{"label": "JNJ", "value": "JNJ"},
	{"label": "UNH", "value": "UNH"},
	{"label": "WMT", "value": "WMT"},
	{"label": "BAC", "value": "BAC"},
	{"label": "HD", "value": "HD"},
	{"label": "ADI", "value": "ADI"},
	{"label": "MA", "value": "MA"},
	{"label": "PG", "value": "PG"},
	{"label": "ASML", "value": "ASML"},
	{"label": "DIS", "value": "DIS"},
	{"label": "ADBE", "value": "ADBE"},
	{"label": "NFLX", "value": "NFLX"},
]

crypto_choices = [
	{"label": "ETH", "value": "ETH"},
	{"label": "LTC", "value": "LTC"},
	{"label": "ADA", "value": "ADA"},
	{"label": "DOT", "value": "DOT"},
	{"label": "BCH", "value": "BCH"},
	{"label": "XLM", "value": "XLM"},
	{"label": "LINK", "value": "LINK"},
	{"label": "BNB", "value": "BNB"},
	{"label": "USDT", "value": "USDT"},
	{"label": "XMR", "value": "XMR"},
]